name: Run ESLint for only modified files
description: ''

inputs:
  lintScript:
    description: The name of npm script
    required: false
    default: lint

runs:
  using: composite
  steps:
    - uses: ./node-yarn@v1
    - name: Run ESLint for only modified files.
      run: yarn ${{ inputs.lintScript }} $(git diff --diff-filter=d origin/HEAD --name-only --cached '*.ts' '*.tsx' '*.js' '*.cjs' '*.mjs')
